### ISSUE TITLE
ModuleNotFoundError: No module named 'polyiou'

### ISSUE THREAD

**Issue by zhangfx123** [flyingshan/Learning-Polar-Encodings-For-Arbitrary-Oriented-Ship-Detection-In-SAR-Images#1]
ModuleNotFoundError: No module named 'polyiou',Is there a file missing here?

**Comment by flyingshan** [comment]
We use the DOTA-devkit as the evaluation tool for our experiments.
You should refer and install it from [at](https://github.com/CAPTAIN-WHU/DOTA_devkit)
It should be placed at /datasets/DOTA_devkit/
