### ISSUE TITLE
请问7×7conv在哪里

### ISSUE THREAD

**Issue by kobezy** [flyingshan/Learning-Polar-Encodings-For-Arbitrary-Oriented-Ship-Detection-In-SAR-Images#8]
你好，请问7×7卷积在哪里？代码中并未体现。感谢回复。

**Comment by flyingshan** [comment]
你是对的，这部分结构和代码参考了 [BBAVectors](https://github.com/yijingru/BBAVectors-Oriented-Object-Detection/tree/master)，但从代码里看其实应该没有用到7x7卷积，这应该是论文描述中的一个bug。
